apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/azure-dns-label-name: {{.Values.dns.prefix}}
  name: {{.Release.Name}}-load-service
  namespace: {{ default "dev" .Release.Namespace }}
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    app: {{ .Values.image.name }}
