apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}-service
  namespace: {{ default "dev" .Release.Namespace }}
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: http
      name: http
  selector:
    app: {{ .Values.image.name }}
  type: ClusterIP
