import {
  DataExport,
  DataImport,
  FolderBrowser,
  GroupForm,
  GroupView,
  MySearch,
  MySubscription,
  PermissionWidget,
  PropertiesWidget,
  RecordCreation,
  HadRecordCreation,
  RecordList,
  ChildRecordList,
  QueryRecordList,
  Report,
  SearchForm,
  MyInbox,
  MyOutbox,
  TaskDetail,
  TaskComment,
  GisWidget,
  EmailEditor,
  SimpleSearch,
  UserAdmin,
  RecordHistory,
  RecordComparison,
  RecordAuditDetail,
  RecordEditHistory,
  WorkflowTreeView,
  HADRecordList,
  HADViewChange,
  RecordHistoryLog,
  Publication,
} from '../widget';
import ContentCreation from '../widget/ContentCreation/SimpleFolderBrowser';
import AutolinkDetailpage from '../widget/organisms/AutoLink/auto-link-detail-page';
import Autolinkpage from '../widget/organisms/AutoLink/auto-link-page';
import BIChart from '../widget/organisms/BIChart/BIChart';
import PositionCreation from '../widget/organisms/PositionCreation/PositionCreation';
import PositionMgmt from '../widget/organisms/PositionMgmt/PositionMgmt';
import RenditionWidget from '../widget/organisms/Rendition/Rendition';
import Versionpage from '../widget/organisms/Version/VersionPage';

const WidgetHandler = {
  Member: <GroupForm />,
  'Org Chart': <GroupView />,
  'Folder Browser': <FolderBrowser />,
  Permission: <PermissionWidget />,
  'Position Creation': <PositionCreation />,
  'Record Creation': <RecordCreation />,
  'Had Record Creation': <HadRecordCreation />,
  'Record List': <RecordList />,
  'Child Record List': <ChildRecordList />,
  'Query Record List': <QueryRecordList />,
  'Position Management' : <PositionMgmt />,
  'Data Import': <DataImport />,
  'Data Export': <DataExport />,
  Properties: <PropertiesWidget />,
  'My Subscriptions': <MySubscription />,
  Report: <Report />,
  'My Search': <MySearch />,
  'Search Form': <SearchForm />,
  'Content Creation': <ContentCreation />,
  Rendition: <RenditionWidget />,
  autolinkpage: <Autolinkpage />,
  AutolinkDetailpage: <AutolinkDetailpage />,
  Version: <Versionpage />,
  'Bar Chart': <BIChart misBiConfigGraphicType={'1'} />,
  'Line Chart': <BIChart misBiConfigGraphicType={'2'} />,
  'Pie Chart': <BIChart misBiConfigGraphicType={'3'} />,
  'Bar Race': <BIChart misBiConfigGraphicType={'4'} />,
  'Line Race': <BIChart misBiConfigGraphicType={'5'} />,
  'My Inbox': <MyInbox />,
  'My Outbox': <MyOutbox />,
  'Task Detail': <TaskDetail />,
  'Task Comment': <TaskComment />,
  GIS: <GisWidget />,
  EmailEditor: <EmailEditor />,
  'Simple Search': <SimpleSearch />,
  'User Admin': <UserAdmin />,
  'Record History': <RecordHistory />,
  'Record History Log': <RecordHistoryLog />,
  'Record Comparison': <RecordComparison />,
  'Record Audit Detail': <RecordAuditDetail />,
  'Record Edit Data': <RecordEditHistory />,
  'Workflow Tree View': <WorkflowTreeView />,
  'HAD Record List': <HADRecordList />,
  'HAD View Change': <HADViewChange />,
  'Publication': <Publication />,
};

export default WidgetHandler;
