const route = {
  audit: '/audit',
  context: '/context',
  contextDetail: '/context/detail',
  dictionary: '/dictionary',
  dictionaryDetail: '/dictionary/detail',
  home: '/',
  login: '/login',
  propertyPage: '/propertypage',
  propertyPageDetail: '/propertypage/detail',
  queryForm: '/queryForm',
  queryFormDetail: '/queryForm/detail',
  systemConfig: '/systemconfig',
  table: '/table',
  tableDetail: '/table/edit',
  tableReference: '/table/ref',
  useradmin: '/useradmin',
  workspace: '/workspace',
  workspaceDetail: '/workspace/config',
  storage: '/storage',
  storageDetail: '/storage/detail',
  biToolConfig: '/biToolConfig',
  biToolDetail: '/biToolDetail',
  biToolChat: '/biToolChat',
  widgetMgmt: '/widgetMgmt',
  widgetMgmtDetail: '/widgetMgmt/detail',
  simpleSearch: '/simpleSearch',
  simpleSearchDetail: '/simpleSearch/detail',
  myProfile: '/myProfile/',
  viewRelationData: '/viewRelationData',
  welcomeConfig: '/welcomeConfig',
  welcomeView: '/welcomeView',
};

export default route;
