const API_ROUTE = {
  loginService: {
    LOGIN: '/userInfo/login',
    FORGOT: '/userInfo/forgotPwd',
    RESET: '/userInfo/reset',
    GET_USER_INFO: '/userInfo/getuserinfo',
    GET_PASSWORD_POLICY: '/userInfo/getPasswordPolicy',
  },
  userService: {
    DEL_GROUP_USER: '/UserRolePerm/delGroupUser',
    DEL_ROLE: '/UserRolePerm/delRole',
    DEL_USER: 'UserRolePerm/delUser',
    FIND_ORG_CHART: '/UserRolePerm/findAllOrgChart',
    GET_GROUP_INFO_BY_ID: '/UserRolePerm/getGroupInfoById',
    GET_MEMBER_INFO_BY_BY_ROLE: '/UserRolePerm/getMemberInfoByRole',
    GET_MEMBER_INFO_BY_GROUP: '/UserRolePerm/getMemberInfoByGroup',
    GET_MEMBER: '/UserRolePerm/getMember',
    GET_USER_INFO_BY_GROUP: '/UserRolePerm/getUserInfoByGroup',
    GET_USER_INFO_BY_ID: '/UserRolePerm/getUserInfoById',
    GET_USER_INFO: '/UserRolePerm/getUserInfoByUserId',
    QUERY_GROUP_DATA: '/UserRolePerm/queryGroupData',
    GET_GROUP_DATA: '/UserRolePerm/getGroupsByUserId',
    QUERY_PERMISSION_DATA: '/userPermission/getAllPermission',
    QUERY_USER_ALL: 'UserRolePerm/queryUserAll',
    GET_MYPROFILE: '/UserRolePerm/getMyProfileByUserId',
    UPDATE_MEMBER_BY_GROUP: '/UserRolePerm/updateMemberByGroup',
    INSERT_MEMBER_BY_ROLE: '/UserRolePerm/insertMemberByRole',
    UPDATE_MEMBER_BY_ROLE: '/UserRolePerm/updateMemberByRole',
    INSERT_MEMBER_BY_GROUP: '/UserRolePerm/insertMemberByGroup',
    QUERY_ALL_GROUP_DATA: '/UserRolePerm/queryAllGroupData',
    GET_WORKFLOW_TREE: '/UserRolePerm/getWorkflowTree',
  },
  userPermission: {
    GET_ALL_PERMISSION: '/userPermission/getAllPermission',
    DEL_PERMISSION: '/userPermission/delPermission',
    SAVE_PERMISSION_DATA: '/userPermission/savePermissionData',
    QUERY_FOLDER_PERMISSION: '/userPermission/queryFolderPermission',
    QUERY_RECORD_PERMISSION: '/userPermission/queryRecordPermission',
    INSERT_PERMISSION_DATA: '/userPermission/insertPermissionData',
    GET_GROUP_DEFAULT_FOLDER: '/userInfo/getGroupDefaultFolderByGroupId',
  },
  context: {
    ADD_CONTEXT: 'context/addContext',
    DELETE_CONTEXT: '/context/deleteContext',
    DETAIL_CONTEXT: '/context/detailContext',
    FIND_CONTEXT_LIST: '/context/findContextList',
    FIND_ROLE_LIST: '/context/findRoleList',
    FIND_WORKSPACE_LIST: '/context/findWorkspaceList',
    UPDATE_CONTEXT: 'context/updateContext',
  },
  workspace: {
    ADD_WORKSPACE: '/workspace/addWorkspace',
    DELETE_WORKSPACE_BY_ID: '/workspace/deleteWorkspaceById',
    EDIT_WORKSPACE: '/workspace/editWorkspace',
    GET_CONTEXT_BY_USER_ID: '/workspace/getContextByUserId',
    GET_WORKSPACE_LIST_PAGABLE: '/workspace/getWorkspaceListPageable',
    SELECT_WORKSPACE_WIDGET_BY_ID: '/workspace/selectWorkspaceWidgetById',
    FIND_PARENT_CANDIDATE_BY_ID: '/workspace/findParentCandidateById',
    SET_PARENT: '/workspace/setParent',
    FIND_ALL_WORKSPACE_LIST: '/workspace/findAllWorkspaceList',
  },
  queryForm: {
    ADD_QUERY_FORM: 'queryForm/addQueryForm',
    DELETE_QUERY_FORM: 'queryForm/deleteQueryForm',
    EDIT_QUERY_FORM: 'queryForm/editQueryFormByMisQueryForm',
    GET_CONTEXT_BY_USER_ID: '/workspace/getContextByUserId',
    GET_QUERY_FORM_BY_ID: 'queryForm/getQueryFormById',
    GET_QUERY_LIST: 'queryForm/getQueryList',
    GET_QUERY_FORM_LIST: 'queryForm/getQueryList',
    GET_TYPE_DIC: '/queryForm/getTypeDic',
    GET_COLUMN_DIC: '/queryForm/getColumnDic',
    GET_QUERY_COLUMN_DIC: '/queryForm/getQueryColumnDic',
    SAVE_SEARCH_FORM: '/queryForm/saveSearchForm',
  },
  folderService: {
    DELETE_FOLDER: '/folder/deleteFolder',
    GET_FOLDER_LIST: '/folder/getFolderList',
    SAVE_FOLDER: '/folder/saveFolder',
    UPDATE_FOLDER: '/folder/updateFolder',
    GET_DEFAULT_FOLDER: '/folder/getDefaultFolder',
  },
  recordService: {
    DEL_PROPERTIES: '/record/deleteProperties',
    GET_FOLDER_RECORD_LIST: '/record/getFolderRecordList',
    GET_DEFAULT_RECORD_LIST: '/record/getDefaultRecordList',
    GET_QUERY_RECORD_LIST: '/record/getQueryRecordList',
    GET_RECORD_LIST: '/record/getRecordListByRecIds',
    GET_PROPERTIES: '/record/getProperties',
    GET_REF_PROPERTIES: '/record/getRefProperties',
    SAVE_PROPERTIES: '/record/saveProperties',
    SEARCH_RECORD: '/record/searchRecord',
    GET_RECORD_HISTORY: '/record/getRecordHistoryByRecId',
    GET_RECORD_HISTORY_LOG: '/record/getRecordHistoryLogByRecId',
    GET_RECORD_COMPARISON: '/record/getRecordComparisonByRecId',
    GET_RECORD_AUDIT_DETAIL: '/record/getRecordAuditDetailByRecId',
    GET_RECORD_EDIT_LIST: '/record/getRecordEditListByRecIds',
    GET_TAB_RECORD_LIST: '/record/getTabRecordList',
    GET_TAB_RECORD_LIST_BY_RECID: '/record/getTabRecordByRecIds',
    GET_TABLE_AND_REF_TAB: '/record/getTableAndRefTab',
    GET_DRAFT_PROPERTIES: '/record/getDraftProperties',
    DEL_DRAFT_PROPERTIES: '/record/deleteDraftProperties',
    SAVE_DRAFT_PROPERTIES: '/record/saveDraftProperties',
  },
  subscription: {
    FOLDER_IS_SUBSCRIBE: '/subscription/folderIsSubscribe',
    UNSUBSCRIPTION: '/subscription/unSubscription',
    SAVE_SUBSCRIPTION: '/subscription/saveSubscription',
    GET_SUBSCRIPTION_MSG: '/subscription/getSubscriptionMsgByUserId',
    DEL_SUBSCRIPTION_MSG: '/subscription/deleteSubscriptionMsgById',
    UPDATE_SUBSCRIPION_MSG_READ: '/subscription/updateSubscriptionMsgRead',
  },
  recordManage: {
    GET_TABLE_COLUMN: '/RecordManage/getTableColumn',
    GET_TABLE_COLUMN_BY_PROPERTY_ID: '/RecordManage/getTableColumnByPropertyId',
    INSERT_TABLE_DATA: '/RecordManage/insertTableData',
    GET_TABLE_NAME: '/RecordManage/getTableName',
    CALC_COLUMN_QUERY_RESULT: '/RecordManage/calcColumnQueryResult',
    UPDATE_TABLE_DATA: '/RecordManage/updateTableData',
    DELETE_TABLE_DATA: '/RecordManage/deleteTableData',
    IS_HAS_PERMISSION: '/RecordManage/isHasPermission',
    EXPORT_PDF_CONTENT: '/RecordManage/exportPDFContent',
    PRINT_TABLE_DATA: '/RecordManage/printTableData',
    GET_RELATION_DATA: '/RecordManage/getRelationData',
    UPDATE_TYPE_RECORD: '/RecordManage/updateTypeRecord',
    GET_TABS_CONF: '/RecordManage/getTabsConf',
    GET_TABS_DATA: '/RecordManage/getTabsData',
    GET_RECORDID_BY_TYPEID: '/RecordManage/getRecordIdByTypeId',
    GET_PROPERTY_BY_TYPEID: '/RecordManage/getPropertyByTypeId',
  },
  dictManage: {
    ADD_DICT_ITEM: 'DictManage/addDicItem',
    DEL_DICT_DETAIL: 'DictManage/delDictionaryDetail',
    DEL_DICT_ITEM: 'DictManage/delDictionaryItem',
    DEL_DICTIONARY: 'DictManage/delDictionary',
    GET_ALL_DIC_NAME: 'DictManage/getAllDictName',
    QUERY_DICT_DETAILS: 'DictManage/queryDictDetails',
    SAVE_DICTIONARY: 'DictManage/createDic',
    UPDATE_DICT_ITEM: 'DictManage/updateDicItem',
    UPDATE_DICTIONARY: 'DictManage/updateDic',
    VERIFY_PROP_SQL: 'DictManage/verifyPropSql',
    GET_DIC_LIST_BY_ID: 'DictManage/getDicListById',
  },
  typeService: {
    ADD_NEW_TYPE: '/type/addNewType',
    DELETE_TYPE: '/type/deleteType',
    GET_ALL_TYPES: '/type/getAllTypes',
    GET_DIC_LIST: '/type/getDicList',
    SELECT_TYPE_BY_ID: '/type/selectTypeById',
    UPDATE_TYPE: '/type/updateType',
    DELETE_COLUMN: '/type/deleteColumn',
    UPDATE_COLUMN: '/type/updateColumn',
    ADD_COLUMN: '/type/addNewColumn',
    ADD_NEW_TYPE_AND_DRAF: '/type/addNewTypeAndDraf',
    CHECK_DEMO_AND_DISS: '/type/checkDemoAndDiss',
    GET_TYPE_PERMISSION: '/type/getTypePermission',
    EDIT_NEW_TYPE_AND_DRAF: '/type/editNewTypeAndDraf',
  },
  property: {
    ADD_PROPERTY_PAGE: '/property/addPropertyPage',
    DELETE_PROPERTY: '/property/deleteProperty',
    EDIT_PROPERTY_PAGE: '/property/editPropertyPage',
    GET_PROPERTY_PAGE: '/property/getPropertyPage',
    SELECT_PROPERTY_BY_ID: '/property/selectPropertyById',
    SAVE_PROPERTY_COLUMN_PERMISSION: '/propertyColumnPermission/editPropertyColumnPermission',
    GET_PROPERTY_COLUMN_PERMISSION: '/propertyColumnPermission/getPropertyColumnPermission',
    SELECT_PROPERTY_CONFIG_DETAIL_BY_ID: '/property/selectPropertyConfigDetailById',
  },
  sysConfig: {
    SAVE_SYS_CONFIG: 'sysConfig/saveSysConfig',
    FIND_SYS_CONFIG_LIST: 'sysConfig/findSysConfigList',
    DELETE_SYS_CONFIG: 'sysConfig/deleteSysConfig',
    GET_WORKFLOW_SWITCH: 'sysConfig/getWorkflowSwitch',
    FIND_BY_KEY: 'sysConfig/findSysConfigByKey',
  },
  organization: {
    DELETE_ORG: 'organization/deleteOrg',
    GET_ORG_LIST: 'organization/getOrgList',
    SAVE_ORGANIZATION: 'organization/saveOrganization',
  },
  auditManage: {
    GET_ALL_AUDIT: '/AuditManage/getAllAudit',
  },
  userAdmin: {
    DEL_USER: 'userAdmin/delUser',
    QUERY_USER_ALL: 'userAdmin/queryUserAll',
    EDIT_USER_DATA: 'userAdmin/editUserData',
    GET_ACCOUNT_SETTING: 'userAdmin/getAccountSetting',
    CHANGE_ACCOUNT_SETTING: 'userAdmin/changeAccountSetting',
    CHANGE_PASSWORD: 'userAdmin/changePassword',
    SEARCH_USER: 'userAdmin/searchUser',
  },
  report: {
    GET_TEMPLATE: '/report/getReportTemplate',
    GET_REPORTS: '/report/getReports',
    GENERATE_REPORT: '/report/generateReport',
    EXPORT_STATISTICS: '/report/generateStatisticsReport',
    EXPORT_INVENTORY: '/report/generateInventoryReport',
    DOWNLOAD_REPORT: '/report/download',
  },
  exportService: {
    exportXls: '/export/excel97',
    exportXlsx: '/export/excel03',
    exportCsv: '/export/csv',
    simpleSearchExport: '/export/simpleSearchExport',
  },
  storage: {
    ADD_STORAGE: 'storage/addNewStorage',
    FIND_STORAGE_LIST: '/storage/getAllStorage',
    UPDATE_STORAGE: 'storage/addNewStorage',
    DELETE_STORAGE: '/storage/deleteStorage',
    DETAIL_STORAGE: '/storage/getStorageById',
  },
  renditionService: {
    UPLOAD_RENDITION: '/rendidtion/upLoadRendition',
    GET_RENDITION_BY_RECORDID: '/rendidtion/getRenditionByRecordId',
    DELETE_RENDITION_BY_RENDITIONID: '/rendidtion/deleteRenditionByRenditionId',
  },
  contentService: {
    UPLOAD_FILES: '/Content/upLoadFile',
    MERGE_CONTENT_CHUMKS_FILE: '/Content/mergeContentChumksFile',
  },
  autolinkManage: {
    QUERY_ALL_TYPES_NO_WITH: '/type/queryAllTypesNoWith',
    QUERY_COLUMN_BY_TYPE_ID: '/type/queryColumnByTypeId',
    DELETE_AUTOLINK_BY_ID: 'Content/deleteAutolinkById',
    GET_ALL_AUTOLINK: 'Content/getAllAutoLink',
    EDIT_AUTOLINK: 'Content/editAutoLink',
    SAVE_AUTOLINK: 'Content/saveAutoLink',
  },
  versionManage: {
    DEL_VERSION: 'Content/delVersion',
    GET_ALL_VERSION: 'Content/queryVersionData',
    DOWNLOAD_FILE: 'Content/downloadFile',
    UP_LOAD_CHECK_FILE: 'Content/UpLoadCheckFile',
    IS_UPLOAD: 'Content/isUpload',
    UPLOAD_BIG_FILE: 'Content/uploadBigFile',
    MERGE_CHUMKS_FILE: 'Content/mergeChumksFile',
    DOWN_BIG_FILE: 'Content/downBigFile',
    DOWN_LOAD_CHUNK_FILE: 'Content/downloadChunkFile',
  },
  typeRefService: {
    GET_ALL_TYPE_REF: '/typeRef/getAllTypeRef',
    ADD_TYPE_REF: '/typeRef/addTypeRef',
    UPDATE_TYPE_REF: '/typeRef/updateTypeRef',
    DELETE_TYPE_REF: '/typeRef/deleteTypeRef',
    GET_CROSS_REF_BY_ID: '/typeRef/getById',
  },
  biTool: {
    GET_ALL_BI_TOOL_BY_PAGE: 'biTool/getAllBiToolByPage',
    GET_ALL_BI_TOOL: 'biTool/getAllBiTool',
    DEL_BI_TOOL: 'biTool/delBiTool',
    GET_BI_TOOL: 'biTool/getBiTool',
    ADD_BI_TOOL: 'biTool/addBiTool',
    EDIT_BI_TOOL: 'biTool/editBiTool',
    QUERY_TABLE_DATA: 'biTool/queryTableData',
    QUERY_COLUMN_DATA: 'biTool/queryColumnData',
    COUNT_TABLE_COLUMN_DATA: 'biTool/countTableColumnData',
    COUNT_TABLE_COLUMN_DATA_BY_DATE: 'biTool/countTableColumnDataByDate',
    COUNT_WORKFLOW_DATA: 'biTool/countWorkFlowData',
    COUNT_WORKFLOW_DATA_BY_DATE: 'biTool/countWorkFlowDataByDate',
  },
  workflow: {
    GET_ALL_PROCESS: '/process/getAllProcess',
    GET_ALL_ACTIVITIES: '/activity/getAllActivities',
    DETAIL_PROCESS: '/process/getProcessById',
    initWorkflow: '/ws/workflow/initWorkflow',
    submitWorkflow: '/ws/workflow/submitWorkflow',
    workflowList: '/task/getWorkflowList',
    changeOwner: '/task/changeOwner',
  },
  myInbox: {
    GET_ALL_INBOX: '/ws/workflow/getMyInboxListByUserId',
    GET_ALL_OUTBOX: '/ws/workflow/getMyOutboxListByUserId',
    GET_ALL_TASK: '/ws/workflow/getTaskListByUserId',
    GET_ATTACHMENTS: '/ws/workflow/getAttachmentsByWfWorkflowId',
    GET_TASK_DETAIL: '/ws/workflow/getTaskDetail',
    ACQUIRE_TASK: '/ws/workflow/acquireTask',
    APPROVE_TASK: '/ws/workflow/approveTask',
    REJECT_TASK: '/ws/workflow/rejectTask',
    DELEGATE_TASK: '/ws/workflow/delegateTask',
    TERMINATE_WORKFLOW: '/ws/workflow/terminateWorkflow',
    WITHDRAW_WORKFLOW: '/ws/workflow/withdrawWorkflow',
    GET_COMMENT: '/ws/workflow/getCommentByWorkflowId',
    SAVE_COMMENT: '/ws/workflow/saveTaskComment',
    GET_COMMENT_BY_TYPE_AND_REC: '/ws/workflow/getCommentByTypeIdAndRecId',
  },
  widget: {
    GET_WIDGET_LIST: '/widget/getWidgetList',
    GET_WIDGET_LIST_BY_PAGE: '/widget/getWidgetListByPage',
    GET_WIDGET_BY_ID: '/widget/getWidgetById',
    GET_SIMPLESEARCH_BY_ID: '/widget/getSimpleSearchById',
    ADD_WIDGET: '/widget/addWidget',
    EDIT_WIDGET: '/widget/editWidget',
    DELETE_WIDGET: '/widget/deleteWidget',
  },
  simpleSearch: {
    GET_SIMPLE_SEARCH_LIST_BY_PAGE: '/simpleSearch/getSimpleSearchListPageable',
    ADD_SIMPLE_SEARCH: '/simpleSearch/addSimpleSearch',
    EDIT_SIMPLE_SEARCH: '/simpleSearch/editSimpleSearch',
    DELETE_SIMPLE_SEARCH: '/simpleSearch/deleteSimpleSearch',
    GET_SIMPLE_SEARCH_BY_ID: '/simpleSearch/getSimpleSearchById',
    SIMPLE_SEARCH_RECORD: '/simpleSearch/simpleSearchRecord',
    GET_SIMPLE_SEARCH_DIC: '/simpleSearch/getSimpleSearchDic',
    GET_HAD_RECORD: '/simpleSearch/getHADRecord',
    GET_HAD_VIEW_CHANGE: '/simpleSearch/getHADViewChange',
  },
  relation: {
    ADD_RELATION: '/relation/addRelation',
    GET_RELATION_BY_TYPE_ID: '/relation/getRelationByTypeId',
    DELETE_RELATION_REC: '/relation/deleteRelationRec',
  },
  publication: {
    INSERT_RECORD: '/publication/InsertRecord',
    UPDATE_RECORD: '/publication/UpdateRecord',
    REMOVE_RECORD: '/publication/RemoveRecord',
    PUBLIC_RECORD: '/publication/PublicRecord',
    SCHEDULE_RECORD: '/publication/ScheduleRecord',
    PUBLIC_RESULT: '/publication/getResult',
  },
  welcomePage: {
    UPLOAD_EDITOR_IMAGE: '/welcome/uploadEditorImage',
    ADD_WELCOMEDATA: '/welcome/addWelcomeData',
    GET_WELCOME: '/welcome/getWelcome',
  },
};

export default API_ROUTE;
